[pytest]
addopts = -ra -q --html=reports/report.html --self-contained-html --reruns 1
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = tests
markers =
    WRITE: tests that create/modify data
    regression: regression test suite
    front_end: front-end UI tests

